//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ContentWhoEntities : DbContext
    {
        public ContentWhoEntities()
            : base("name=ContentWhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Jurisdiction> Jurisdictions { get; set; }
        public DbSet<PracticeArea> PracticeAreas { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Segment> Segments { get; set; }
        public DbSet<UserList> UserLists { get; set; }
        public DbSet<ProductOwner> ProductOwners { get; set; }
    }
}
