//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Acronym { get; set; }
        public int PracticeAreaId { get; set; }
        public string PracticeAreaLead { get; set; }
        public int SegmentId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime LastEditedOn { get; set; }
        public string LastEditedBy { get; set; }
        public int JurisdictionId { get; set; }
        public string REPEditor { get; set; }
        public string Url { get; set; }
        public string Manager { get; set; }
    
        public virtual Jurisdiction Jurisdiction { get; set; }
        public virtual PracticeArea PracticeArea { get; set; }
        public virtual Segment Segment { get; set; }
    }
}
